{{- $multiple := gt (len $.Values.jobs) 1 -}}
{{- range $index, $job := $.Values.jobs }}
{{- $nameSuffix := ternary (printf "-%s" $job.name) "" $multiple -}}
{{- if gt $index 0 }}
---
{{- end }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" $ }}{{ $nameSuffix }}
  labels:
    {{- include "cronjob.labels" $ | nindent 4 }}
spec:
  schedule: {{ default "0 4 * * *" $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $.Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $.Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "cronjob.selectorLabels" $ | nindent 12 }}
        spec:
          activeDeadlineSeconds: {{ $.Values.cronjob.activeDeadlineSeconds }}
          restartPolicy: {{ $.Values.cronjob.restartPolicy }}
          securityContext:
            fsGroup: 1000
          containers:
          - name: {{ $.Chart.Name }}
            image: "{{ $.Values.cronjob.image.repository }}:{{ $.Values.cronjob.image.tag }}"
            imagePullPolicy: {{ $.Values.cronjob.image.pullPolicy }}
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            envFrom:
            - secretRef:
                name: {{ $.Values.secret.name }}
            - configMapRef:
                name: {{ include "cronjob.fullname" $ }}-config{{ $nameSuffix }}
            volumeMounts:
            - name: token-cache
              mountPath: {{ dir $.Values.cacheFilePath | quote }}
              readOnly: false
          volumes:
          - name: token-cache
            persistentVolumeClaim:
              claimName: {{ $.Values.persistentVolumeClaim.name }}
{{- end }}
