{{- $multiple := gt (len $.Values.jobs) 1 -}}
{{- range $index, $job := $.Values.jobs }}
{{- $nameSuffix := ternary (printf "-%s" $job.name) "" $multiple -}}
{{- $jobTimeZone := coalesce $job.timeZone $.Values.cronjob.timeZone -}}
{{- if gt $index 0 }}
---
{{- end }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" $ }}{{ $nameSuffix }}
  labels:
    {{- include "cronjob.labels" $ | nindent 4 }}
spec:
  schedule: {{ default "0 4 * * *" $job.schedule | quote }}
{{- if $jobTimeZone }}
  timeZone: {{ $jobTimeZone | quote }}
{{- end }}
  successfulJobsHistoryLimit: {{ $.Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $.Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "cronjob.labels" $ | nindent 8 }}
        app: {{ include "cronjob.fullname" $ }}{{ $nameSuffix }}
        cronjob: {{ include "cronjob.fullname" $ }}{{ $nameSuffix }}
    spec:
      template:
        metadata:
          labels:
            {{- include "cronjob.selectorLabels" $ | nindent 12 }}
            {{- with $.Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          activeDeadlineSeconds: {{ $.Values.cronjob.activeDeadlineSeconds }}
          restartPolicy: {{ $.Values.cronjob.restartPolicy }}
          serviceAccountName: {{ $.Values.serviceAccount.name }}
          securityContext:
            fsGroup: 1000
          containers:
          - name: {{ $.Chart.Name }}
            image: "{{ $.Values.cronjob.image.repository }}:{{ $.Values.cronjob.image.tag | default $.Chart.AppVersion }}"
            imagePullPolicy: {{ $.Values.cronjob.image.pullPolicy }}
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            envFrom:
            - secretRef:
                name: {{ $.Values.secret.name }}
            - configMapRef:
                name: {{ include "cronjob.fullname" $ }}-config{{ $nameSuffix }}
{{- if $jobTimeZone }}
            env:
            - name: TZ
              value: {{ $jobTimeZone | quote }}
{{- end }}
            volumeMounts:
            - name: spotify-token
              mountPath: {{ $.Values.tokenSecret.mountPath | quote }}
              readOnly: true
          volumes:
          - name: spotify-token
            secret:
              secretName: {{ $.Values.tokenSecret.name }}
              optional: true
{{- end }}
