services:
  playlist-generator:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/cache/:/app/cache/
    env_file:
      - .env
    environment:
      - IS_RUNNING_IN_CONTAINER=true
      - TOKEN_CACHE_FILE_PATH=/app/cache/token_cache.txt
